### ISSUE TITLE
[suggestion] better alternative

### ISSUE THREAD

**Issue by dnmTX** [dead-hosts/hosts_git_tyzbit#1]
@funilrys   tyzbit stoped maintaining that lists long time ago(since StevenBlack drop it from his lists due to complains) .I'd recommend switching to: 
1.  https://github.com/crazy-max/WindowsSpyBlocker/tree/master/data   # plenty of choice
2. https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/spy.txt   # hosts

Be aware though,there will be complains about "false positives" if you use it in your Ultimate.Hosts.Blacklist,
if not,just being filtered here is still something and i'm pretty sure that @crazy-max would appreciate it.

**Comment by funilrys** [comment]
Hi @dnmTX, as said at https://github.com/dead-hosts/cameleon_web_sysctl.org/issues/1#issuecomment-395989346, this repository will never be deleted nor archived until @dead-hosts/tyzbit do it or explitly tell me to do so. 

If @crazy-max want it (like every other list maintainers) or if it benefits to many, I can create a testing repositories + team for those repository!

Cheers,
Nissar

**Comment by crazy-max** [comment]
Hi guys,

In the latest release of WindowsSpyBlocker i have implemented a test menu for domains lookup :

![image](https://user-images.githubusercontent.com/1951866/41439128-d68e1e80-7029-11e8-8a05-f6fc52dc121c.png)

I consider a domain active if :

* I can [lookup the IP address](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/app/cmds/dev/test/hosts.go#L59)
* or I can [lookup the CNAME](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/app/cmds/dev/test/hosts.go#L74)
* or I can [lookup the NS](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/app/cmds/dev/test/hosts.go#L87)

For firewall IP adresses i use multi providers API like [whatismyipaddress.com, ip-api.com, etc...](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/app/settings.json#L5-L9) and threatcrowd for a resolution history. (see [CSV files in logs folder](https://github.com/crazy-max/WindowsSpyBlocker/tree/master/logs) on the repo).

But i think it would be nice if we can use PyFunceble in conjunction with my implementation!
I had already thought about doing daily tests with a dedicated repository but if we can work together on that why not! :)

**Comment by dnmTX** [comment]
It's settled then 😎

**Comment by funilrys** [comment]
Extra: https://github.com/dead-hosts/WindowsSpyBlocker-extra_git_crazy-max
Spy: https://github.com/dead-hosts/WindowsSpyBlocker-spy_git_crazy-max
Update: https://github.com/dead-hosts/WindowsSpyBlocker-update_git_crazy-max

@crazy-max Welcome in Dead-Hosts (sent you all invitations) :tada:

**Comment by funilrys** [comment]
@dnmTX From now please start new issues at https://github.com/dead-hosts/dev-center :+1: 

Have a nice day/night.

Cheers,
Nissar

**Comment by dnmTX** [comment]
@funilrys  mine as well move it on the top so to be easily seen an i will.

Have a nice day/night

**Comment by funilrys** [comment]
Pinned.

_______
Closing.
